### ISSUE TITLE
Student Dashboard

### ISSUE THREAD

**Issue by henokkh** [chingu-voyages/v42-bears-team-27#37]
**User Story Description**
As a student
I want to see my dashboard
So I can have a high-level overview of what activities I am currently engaged in, and what tasks are scheduled for that day

**Tasks**
- [x] Create StudentAppBar component
- [x] Create StudentBottomNav component
- [x] Add any existing components for the following screens: **learn**, **home**, and **profile**
