### ISSUE TITLE
Set up CI/CD

### ISSUE THREAD

**Issue by Eloi-Perez** [chingu-voyages/v42-bears-team-27#47]
**__Task Description__**
At the end of each sprint we will deploy the app, so we need to have ready the necessary tools for Continuos Integration & Continuos Deployment

**__ Tasks (to do in this order) __**
- [x] Step up MongoDB Atlas
- [x] Step up Render
- [x] Set up Vercel

**__Technical Considerations__**

**__Additional Considerations__**
We may need to discuss about how are we creating the accounts.

Comments welcome.

**Comment by Eloi-Perez** [comment]
Hey @samad13 I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/chingu-v42-bears-27-63b6f0aebe588b002b403e7a/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account.
  _Posted using [Zenhub](https://www.zenhub.com)_
